#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Tue Oct  2 13:03:34 2007 from /home/jayshree/frames/PrefEvtLogTimestamp.wxg

import wx
import wx.calendar

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizer_4_staticbox = wx.StaticBox(self, -1, "Domain event log timestamp")
        self.calendar_ctrl_1 = wx.calendar.CalendarCtrl(self, -1)
        self.spin_ctrl_1 = wx.SpinCtrl(self, -1, "", min=0, max=100)
        self.label_10 = wx.StaticText(self, -1, ":")
        self.spin_ctrl_2 = wx.SpinCtrl(self, -1, "", min=0, max=100)
        self.label_11 = wx.StaticText(self, -1, ":")
        self.spin_ctrl_3 = wx.SpinCtrl(self, -1, "", min=0, max=100)
        self.label_8 = wx.StaticText(self, -1, "Current timestamp")
        self.label_9 = wx.StaticText(self, -1, "Invalid time")
        self.button_5 = wx.Button(self, -1, "OK")
        self.button_6 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
	
	# Binding the OK and Cancel buttons to the methods 
	self.Bind(wx.EVT_BUTTON, self.Ok_Button_Handler, self.button_5)
	self.Bind(wx.EVT_BUTTON, self.Cancel_Button_Handler, self.button_6)

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle("Domain event log timestamp")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        grid_sizer_8 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_9 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        grid_sizer_10 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_11 = wx.FlexGridSizer(1, 5, 0, 0)
        grid_sizer_10.Add(self.calendar_ctrl_1, 0, 0, 0)
        grid_sizer_11.Add(self.spin_ctrl_1, 0, 0, 0)
        grid_sizer_11.Add(self.label_10, 0, 0, 0)
        grid_sizer_11.Add(self.spin_ctrl_2, 0, 0, 0)
        grid_sizer_11.Add(self.label_11, 0, 0, 0)
        grid_sizer_11.Add(self.spin_ctrl_3, 0, 0, 0)
        grid_sizer_11.AddGrowableRow(0)
        grid_sizer_11.AddGrowableCol(0)
        grid_sizer_10.Add(grid_sizer_11, 1, wx.EXPAND, 0)
        grid_sizer_10.Add(self.label_8, 0, 0, 0)
        grid_sizer_10.Add(self.label_9, 0, 0, 0)
        grid_sizer_10.AddGrowableRow(0)
        grid_sizer_10.AddGrowableCol(0)
        sizer_4.Add(grid_sizer_10, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_9.Add((170, 20), 0, 0, 0)
        grid_sizer_9.Add(self.button_5, 0, 0, 0)
        grid_sizer_9.Add(self.button_6, 0, 0, 0)
        grid_sizer_9.AddGrowableRow(0)
        grid_sizer_9.AddGrowableCol(0)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_8)
        grid_sizer_8.Fit(self)
        grid_sizer_8.AddGrowableRow(0)
        grid_sizer_8.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def Ok_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	print "destroy the child frame"	
	self.Destroy()
		
    def Cancel_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()
# end of class MyFrame2


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_3 = MyFrame2(None, -1, "")
    app.SetTopWindow(frame_3)
    frame_3.Show()
    app.MainLoop()
