#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Fri Sep 28 17:20:54 2007 from /home/jayshree/frames/ResourcePref.wxg

import wx

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_3_copy_staticbox = wx.StaticBox(self, -1, "Resource Severity")
        self.sizer_4_copy_staticbox = wx.StaticBox(self, -1, "Resource Tag")
        self.sizer_2_copy_staticbox = wx.StaticBox(self, -1, "ResourceInfo")
        self.label_1_copy = wx.StaticText(self, -1, "AuxFirmware revision")
        self.label_2_copy = wx.StaticText(self, -1, "Firmware minor revision")
        self.label_3_copy = wx.StaticText(self, -1, "Firmware major revision")
        self.label_4_copy = wx.StaticText(self, -1, "ProductId")
        self.label_5_copy = wx.StaticText(self, -1, "ManufacturerId")
        self.label_6_copy = wx.StaticText(self, -1, "Device support")
        self.label_7_copy = wx.StaticText(self, -1, "Specific version")
        self.label_8_copy = wx.StaticText(self, -1, "Resource revision")
        self.combo_box_1_copy = wx.ComboBox(self, -1, choices=["critical", "Major", "Minor", "Informational", "Normal", "Debug"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.text_ctrl_1_copy = wx.TextCtrl(self, -1, "")
        self.button_2_copy = wx.Button(self, -1, "OK", style=wx.BU_BOTTOM)
        self.button_3_copy = wx.Button(self, -1, "Cancel", style=wx.BU_BOTTOM)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Resource Preferences")
        self.combo_box_1_copy.SetSelection(0)
        self.text_ctrl_1_copy.SetMinSize((220, 27))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        grid_sizer_1_copy = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_4_copy = wx.GridSizer(1, 3, 0, 0)
        sizer_4_copy = wx.StaticBoxSizer(self.sizer_4_copy_staticbox, wx.HORIZONTAL)
        sizer_3_copy = wx.StaticBoxSizer(self.sizer_3_copy_staticbox, wx.HORIZONTAL)
        sizer_2_copy = wx.StaticBoxSizer(self.sizer_2_copy_staticbox, wx.HORIZONTAL)
        grid_sizer_3_copy = wx.GridSizer(8, 1, 0, 0)
        grid_sizer_3_copy.Add(self.label_1_copy, 0, 0, 0)
        grid_sizer_3_copy.Add(self.label_2_copy, 0, 0, 0)
        grid_sizer_3_copy.Add(self.label_3_copy, 0, 0, 0)
        grid_sizer_3_copy.Add(self.label_4_copy, 0, 0, 0)
        grid_sizer_3_copy.Add(self.label_5_copy, 0, 0, 0)
        grid_sizer_3_copy.Add(self.label_6_copy, 0, 0, 0)
        grid_sizer_3_copy.Add(self.label_7_copy, 0, 0, 0)
        grid_sizer_3_copy.Add(self.label_8_copy, 0, 0, 0)
        sizer_2_copy.Add(grid_sizer_3_copy, 1, wx.EXPAND, 0)
        grid_sizer_1_copy.Add(sizer_2_copy, 1, wx.EXPAND, 0)
        sizer_3_copy.Add(self.combo_box_1_copy, 0, 0, 0)
        grid_sizer_1_copy.Add(sizer_3_copy, 1, wx.EXPAND, 0)
        sizer_4_copy.Add(self.text_ctrl_1_copy, 0, wx.EXPAND, 0)
        grid_sizer_1_copy.Add(sizer_4_copy, 1, wx.EXPAND, 0)
        grid_sizer_4_copy.Add((50, 20), 0, 0, 0)
        grid_sizer_4_copy.Add(self.button_2_copy, 0, 0, 0)
        grid_sizer_4_copy.Add(self.button_3_copy, 0, 0, 0)
        grid_sizer_1_copy.Add(grid_sizer_4_copy, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1_copy)
        grid_sizer_1_copy.Fit(self)
        grid_sizer_1_copy.AddGrowableRow(0)
        grid_sizer_1_copy.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

# end of class MyDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = (None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
