#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Fri Sep 28 17:20:54 2007 from /home/jayshree/frames/ResourcePref.wxg

import wx

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
	# begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Resource Severity")
        self.sizer_4_staticbox = wx.StaticBox(self, -1, "Resource Tag")
        self.sizer_2_staticbox = wx.StaticBox(self, -1, "ResourceInfo")
        self.label_1 = wx.StaticText(self, -1, "AuxFirmware revision")
        self.label_2 = wx.StaticText(self, -1, "Firmware minor revision")
        self.label_3 = wx.StaticText(self, -1, "Firmware major revision")
        self.label_4 = wx.StaticText(self, -1, "ProductId")
        self.label_5 = wx.StaticText(self, -1, "ManufacturerId")
        self.label_6 = wx.StaticText(self, -1, "Device support")
        self.label_7 = wx.StaticText(self, -1, "Specific version")
        self.label_8 = wx.StaticText(self, -1, "Resource revision")
        self.combo_box_1 = wx.ComboBox(self, -1, choices=["critical", "Major", "Minor", "Informational", "Normal", "Debug"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.button_2 = wx.Button(self, -1, "OK", style=wx.BU_BOTTOM)
        self.button_3 = wx.Button(self, -1, "Cancel", style=wx.BU_BOTTOM)

        self.__set_properties()
        self.__do_layout()
	# Binding the OK and Cancel buttons to the methods 
	self.Bind(wx.EVT_BUTTON, self.Ok_Button_Handler, self.button_2)
	self.Bind(wx.EVT_BUTTON, self.Cancel_Button_Handler, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Resource Preferences")
        self.combo_box_1.SetSelection(0)
        self.text_ctrl_1.SetMinSize((220, 27))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_4 = wx.GridSizer(1, 3, 0, 0)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
        grid_sizer_3 = wx.GridSizer(8, 1, 0, 0)
        grid_sizer_3.Add(self.label_1, 0, 0, 0)
        grid_sizer_3.Add(self.label_2, 0, 0, 0)
        grid_sizer_3.Add(self.label_3, 0, 0, 0)
        grid_sizer_3.Add(self.label_4, 0, 0, 0)
        grid_sizer_3.Add(self.label_5, 0, 0, 0)
        grid_sizer_3.Add(self.label_6, 0, 0, 0)
        grid_sizer_3.Add(self.label_7, 0, 0, 0)
        grid_sizer_3.Add(self.label_8, 0, 0, 0)
        sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_3.Add(self.combo_box_1, 0, 0, 0)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_4.Add((50, 20), 0, 0, 0)
        grid_sizer_4.Add(self.button_2, 0, 0, 0)
        grid_sizer_4.Add(self.button_3, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade


    def Ok_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()
	
    def Cancel_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()

# end of class MyDialog

