#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Fri Sep 28 17:24:01 2007 from /home/jayshree/frames/Watchdog.wxg

import wx

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog3.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.sizer_4_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "Watchdog timer use expiration flags")
        self.sizer_3_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Watchdog Configuration")
        self.label_23 = wx.StaticText(self.notebook_1_pane_1, -1, "Watchdog log")
        self.checkbox_2 = wx.CheckBox(self.notebook_1_pane_1, -1, "TRUE")
        self.label_24 = wx.StaticText(self.notebook_1_pane_1, -1, "Watchdog running")
        self.checkbox_3 = wx.CheckBox(self.notebook_1_pane_1, -1, "FALSE")
        self.label_25 = wx.StaticText(self.notebook_1_pane_1, -1, "Timer use")
        self.combo_box_5 = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["none", "BIOS FRB2", "BIOS post", "OS lead", "SMS OS", "OEM", "Unspecified"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.label_26 = wx.StaticText(self.notebook_1_pane_1, -1, "Timer action")
        self.combo_box_6 = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["no action", "reset", "power down", "power cycle"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.label_27 = wx.StaticText(self.notebook_1_pane_1, -1, "Pretimer interrupt")
        self.combo_box_7 = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["none", "SMI", "NMI", "Message interrupt", "OEM interrupt"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.label_28 = wx.StaticText(self.notebook_1_pane_1, -1, "Pretimeout interval")
        self.spin_ctrl_3 = wx.SpinCtrl(self.notebook_1_pane_1, -1 )
        self.label_31 = wx.StaticText(self.notebook_1_pane_1, -1, "(ms)")
        self.label_29 = wx.StaticText(self.notebook_1_pane_1, -1, "Initial counter")
        self.spin_ctrl_4 = wx.SpinCtrl(self.notebook_1_pane_1, -1 )
	self.spin_ctrl_5 = wx.SpinCtrl(self.notebook_1_pane_1, -1 )
        self.label_32 = wx.StaticText(self.notebook_1_pane_1, -1, "(ms)")
        self.label_30 = wx.StaticText(self.notebook_1_pane_1, -1, "Present counter")
        self.checkbox_4 = wx.CheckBox(self.notebook_1_pane_2, -1, "BIOS FRB2")
        self.checkbox_5 = wx.CheckBox(self.notebook_1_pane_2, -1, "BIOS post")
        self.checkbox_6 = wx.CheckBox(self.notebook_1_pane_2, -1, "OS lead")
        self.checkbox_7 = wx.CheckBox(self.notebook_1_pane_2, -1, "SMS OS")
        self.checkbox_8 = wx.CheckBox(self.notebook_1_pane_2, -1, "OEM")
        self.button_14 = wx.Button(self, -1, "OK")
        self.button_13 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

	# Binding the OK and Cancel buttons to the methods 
	self.Bind(wx.EVT_BUTTON, self.Ok_Button_Handler, self.button_14)
	self.Bind(wx.EVT_BUTTON, self.Cancel_Button_Handler, self.button_13)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog3.__set_properties
        self.SetTitle("Control Preferrences")
        self.checkbox_2.SetValue(1)
        self.checkbox_3.SetValue(1)
        self.combo_box_5.SetSelection(0)
        self.combo_box_6.SetSelection(0)
        self.combo_box_7.SetSelection(0)
        self.checkbox_5.SetValue(0)
        self.checkbox_6.SetValue(0)
        self.checkbox_7.SetValue(0)
        self.checkbox_8.SetValue(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog3.__do_layout
        grid_sizer_18 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_22 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        grid_sizer_23 = wx.FlexGridSizer(5, 1, 0, 0)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
        grid_sizer_19 = wx.FlexGridSizer(8, 2, 0, 0)
        grid_sizer_21 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_20 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_19.Add(self.label_23, 0, 0, 0)
        grid_sizer_19.Add(self.checkbox_2, 0, 0, 0)
        grid_sizer_19.Add(self.label_24, 0, 0, 0)
        grid_sizer_19.Add(self.checkbox_3, 0, 0, 0)
        grid_sizer_19.Add(self.label_25, 0, 0, 0)
        grid_sizer_19.Add(self.combo_box_5, 0, 0, 0)
        grid_sizer_19.Add(self.label_26, 0, 0, 0)
        grid_sizer_19.Add(self.combo_box_6, 0, 0, 0)
        grid_sizer_19.Add(self.label_27, 0, 0, 0)
        grid_sizer_19.Add(self.combo_box_7, 0, 0, 0)
        grid_sizer_19.Add(self.label_28, 0, 0, 0)
        grid_sizer_20.Add(self.spin_ctrl_3, 0, wx.EXPAND, 0)
        grid_sizer_20.Add(self.label_31, 0, 0, 0)
        grid_sizer_20.AddGrowableRow(0)
        grid_sizer_20.AddGrowableCol(0)
        grid_sizer_19.Add(grid_sizer_20, 1, wx.EXPAND, 0)
        grid_sizer_19.Add(self.label_29, 0, 0, 0)
        grid_sizer_21.Add(self.spin_ctrl_4, 0, 0, 0)
        grid_sizer_21.Add(self.label_32, 0, 0, 0)
	grid_sizer_21.AddGrowableRow(0)
        grid_sizer_21.AddGrowableCol(0)
        grid_sizer_19.Add(grid_sizer_21, 1, wx.EXPAND, 0)
        grid_sizer_19.Add(self.label_30, 0, 0, 0)
	grid_sizer_19.Add(self.spin_ctrl_5, 0, 0, 0)
        grid_sizer_19.AddGrowableRow(0)
        grid_sizer_19.AddGrowableCol(0)
        sizer_3.Add(grid_sizer_19, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_3)
        grid_sizer_23.Add(self.checkbox_4, 0, 0, 0)
        grid_sizer_23.Add(self.checkbox_5, 0, 0, 0)
        grid_sizer_23.Add(self.checkbox_6, 0, 0, 0)
        grid_sizer_23.Add(self.checkbox_7, 0, 0, 0)
        grid_sizer_23.Add(self.checkbox_8, 0, 0, 0)
        grid_sizer_23.AddGrowableRow(0)
        grid_sizer_23.AddGrowableCol(0)
        sizer_4.Add(grid_sizer_23, 1, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetSizer(sizer_4)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "General")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Watchdog flags")
        grid_sizer_18.Add(self.notebook_1, 1, wx.EXPAND, 0)
        grid_sizer_22.Add((170, 20), 0, 0, 0)
        grid_sizer_22.Add(self.button_14, 0, 0, 0)
        grid_sizer_22.Add(self.button_13, 0, 0, 0)
        grid_sizer_22.AddGrowableRow(0)
        grid_sizer_22.AddGrowableCol(0)
        grid_sizer_18.Add(grid_sizer_22, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_18)
        grid_sizer_18.Fit(self)
        grid_sizer_18.AddGrowableRow(0)
        grid_sizer_18.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def Ok_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	print "destroy the child frame"	
	self.Destroy()
		
    def Cancel_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()
# end of class MyDialog3

