#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Fri Sep 28 17:23:20 2007 from /home/jayshree/frames/ControlPref.wxg

import wx

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Control type")
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "Write only control")
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "Control output type")
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Default mode")
        self.label_5 = wx.StaticText(self.notebook_1_pane_1, -1, "Read only control mode")
        self.label_6 = wx.StaticText(self.notebook_1_pane_1, -1, "Control default state")
        self.label_7 = wx.StaticText(self.notebook_1_pane_2, -1, "Control current state")
	
	self.label_21 = wx.StaticText(self.notebook_1_pane_1, -1, "")
	self.label_22 = wx.StaticText(self.notebook_1_pane_1, -1, "")
	self.label_23 = wx.StaticText(self.notebook_1_pane_1, -1, "")
	
        self.combo_box_2 = wx.ComboBox(self.notebook_1_pane_2, -1, choices=["on", "off", "pulse on"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.label_8 = wx.StaticText(self.notebook_1_pane_2, -1, "Control current mode")
        self.combo_box_3 = wx.ComboBox(self.notebook_1_pane_2, -1, choices=["auto", "manual"], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.button_3 = wx.Button(self, -1, "OK")
        self.button_4 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        
	# Binding the OK and Cancel buttons to the methods 
	self.Bind(wx.EVT_BUTTON, self.Ok_Button_Handler, self.button_3)
	self.Bind(wx.EVT_BUTTON, self.Cancel_Button_Handler, self.button_4)
	
	# end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Control Preferences")
        self.combo_box_2.SetSelection(0)
        self.combo_box_3.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        grid_sizer_2 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(12, 1, 0, 0)
        grid_sizer_4.Add(self.label_1, 0, 0, 0)
        grid_sizer_4.Add(self.label_2, 0, 0, 0)
        grid_sizer_4.Add(self.label_3, 0, 0, 0)
        grid_sizer_4.Add(self.label_4, 0, 0, 0)
        grid_sizer_4.Add(self.label_5, 0, 0, 0)
        grid_sizer_4.Add(self.label_6, 0, 0, 0)
	grid_sizer_4.Add(self.label_21, 0, 0, 0)
	grid_sizer_4.Add(self.label_22, 0, 0, 0)
	grid_sizer_4.Add(self.label_23, 0, 0, 0)
        self.notebook_1_pane_1.SetSizer(grid_sizer_4)
        grid_sizer_4.AddGrowableRow(0)
        grid_sizer_5.Add(self.label_7, 0, 0, 0)
        grid_sizer_5.Add(self.combo_box_2, 0, 0, 0)
        grid_sizer_5.Add(self.label_8, 0, 0, 0)
        grid_sizer_5.Add(self.combo_box_3, 0, 0, 0)
        self.notebook_1_pane_2.SetSizer(grid_sizer_5)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "General")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Control state")
        grid_sizer_2.Add(self.notebook_1, 1, wx.EXPAND, 0)
        grid_sizer_3.Add((170, 20), 0, 0, 0)
        grid_sizer_3.Add(self.button_3, 0, 0, 0)
        grid_sizer_3.Add(self.button_4, 0, 0, 0)
        grid_sizer_3.AddGrowableRow(0)
        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_2)
        grid_sizer_2.Fit(self)
        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableCol(0)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MyDialog
    def Ok_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()
	
    def Cancel_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()
