#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Thu Oct 11 13:03:32 2007 from /home/jayshree/Hpiview backups/New frames Sep 07/FrmHelpAbout.wxg

import wx

class frmHelpAbout(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frmHelpAbout.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "OpenHPI View Ver.\n\nwxPython based GUI developed as part of OpenHPI.\n\nDeveloper : Jayashree Padmanabhan")
        self.button_1 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
	self.Bind(wx.EVT_BUTTON, self.Cancel_Button_Handler, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frmHelpAbout.__set_properties
        self.SetTitle("About")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frmHelpAbout.__do_layout
        grid_sizer_3 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_3.Add(self.label_1, 0, wx.EXPAND, 0)
        grid_sizer_4.Add((300, 20), 0, 0, 0)
        grid_sizer_4.Add((10, 20), 0, 0, 0)
        grid_sizer_4.Add(self.button_1, 0, 0, 0)
        grid_sizer_4.AddGrowableRow(0)
        grid_sizer_4.AddGrowableCol(0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_3)
        grid_sizer_3.Fit(self)
        grid_sizer_3.AddGrowableRow(0)
        grid_sizer_3.AddGrowableCol(0)
        self.Layout()
        self.Centre()
        # end wxGlade
   
    def Cancel_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()
# end of class frmHelpAbout



