#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Tue Oct  2 12:46:00 2007 from /home/jayshree/Dialogs/ResEventLog

import wx

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.sizer_2_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "Event log entries")
        self.sizer_3_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "Event log entry info")
        self.sizer_1_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Event log info")
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Active entries count")
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "Maximun entries")
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "Maximum size of user buffer")
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Last update time")
        self.label_5 = wx.StaticText(self.notebook_1_pane_1, -1, "Current event log timestamp")
        self.label_6 = wx.StaticText(self.notebook_1_pane_1, -1, "Event log is overflowed")
        self.label_7 = wx.StaticText(self.notebook_1_pane_1, -1, "Overflow is resetable")
        self.label_8 = wx.StaticText(self.notebook_1_pane_1, -1, "Event log behaviour while over")
        self.checkbox_1 = wx.CheckBox(self.notebook_1_pane_1, -1, "Event log enable state")
        self.button_3 = wx.Button(self.notebook_1_pane_1, -1, "Overflow reset")
        self.list_ctrl_1 = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.button_4 = wx.Button(self.notebook_1_pane_2, -1, "Add entry")
        self.button_5 = wx.Button(self.notebook_1_pane_2, -1, "Clear Log")
        self.button_1 = wx.Button(self, -1, "OK")
        self.button_2 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
	
	# Binding the OK and Cancel buttons to the methods 
	self.Bind(wx.EVT_BUTTON, self.Ok_Button_Handler, self.button_1)
	self.Bind(wx.EVT_BUTTON, self.Cancel_Button_Handler, self.button_2)

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Event log")
        self.checkbox_1.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_6 = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
        grid_sizer_7 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_8 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_1 = wx.StaticBoxSizer(self.sizer_1_staticbox, wx.HORIZONTAL)
        grid_sizer_5 = wx.FlexGridSizer(8, 1, 0, 0)
        grid_sizer_5.Add(self.label_1, 0, 0, 0)
        grid_sizer_5.Add(self.label_2, 0, 0, 0)
        grid_sizer_5.Add(self.label_3, 0, 0, 0)
        grid_sizer_5.Add(self.label_4, 0, 0, 0)
        grid_sizer_5.Add(self.label_5, 0, 0, 0)
        grid_sizer_5.Add(self.label_6, 0, 0, 0)
        grid_sizer_5.Add(self.label_7, 0, 0, 0)
        grid_sizer_5.Add(self.label_8, 0, 0, 0)
        grid_sizer_5.AddGrowableRow(0)
        grid_sizer_5.AddGrowableCol(0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_1, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.checkbox_1, 0, 0, 0)
        grid_sizer_4.Add(self.button_3, 0, 0, 0)
        grid_sizer_4.AddGrowableRow(0)
        grid_sizer_4.AddGrowableCol(0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(grid_sizer_3)
        grid_sizer_3.AddGrowableRow(0)
        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_7.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(self.button_4, 0, 0, 0)
        grid_sizer_8.Add(self.button_5, 0, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)
        grid_sizer_7.AddGrowableRow(0)
        grid_sizer_7.AddGrowableCol(0)
        sizer_2.Add(grid_sizer_7, 1, wx.EXPAND, 0)
        grid_sizer_6.Add(sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_6.Add(sizer_3, 1, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetSizer(grid_sizer_6)
        grid_sizer_6.AddGrowableRow(0)
        grid_sizer_6.AddGrowableCol(0)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "General")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Event log entries")
        grid_sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add((170, 20), 0, 0, 0)
        grid_sizer_2.Add(self.button_1, 0, 0, 0)
        grid_sizer_2.Add(self.button_2, 0, 0, 0)
        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def Ok_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	print "destroy the child frame"	
	self.Destroy()
		
    def Cancel_Button_Handler(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()
# end of class MyDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Dialog_1 = MyDialog(None, -1, "")
    app.SetTopWindow(Dialog_1)
    Dialog_1.Show()
    app.MainLoop()
